### ISSUE TITLE
@todo

### ISSUE THREAD

**Issue by oucar** [oucar/2d-action#6]
- [ ] Changing the weapon from the code
- [ ] Interaction with a chest
- [ ] Getting a random weapon from the chest
- [ ] Enemies can follow the player
- [ ] Enemies can attack (enemy.HP--) if collision occurs
- [ ] More enemies
- [ ] Enemy sprites will play the "idle" animation when player hits them
- [ ] Player can collect money
- [ ] Money will be displayed on the screen
- [ ] HP will be displayed on the screen
- [ ] Player can refill his health by purchasing potion from an NPC.
- [ ] Simple sound effects for critical animations (die, hit etc.) 
- [ ] A simple story
- [ ] A dungeon
